name: pull_request_review workflow

on: [pull_request_review]

jobs:

  build: 
    runs-on: windows-latest
    steps:
      - name: Print build
        run: echo 'build'

  test:
    runs-on: windows-latest
    steps:
      - name: Print test
        run: echo 'test'


  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Print deploy
        run: echo 'deploy'
